/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Keerthi Sreerangaiah
 */
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.*;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JFileChooser;

public class DocumentsCandidate extends javax.swing.JFrame {
Connection conn =null;
ResultSet rs=null;
PreparedStatement pst=null;    
String username;  // declare as Global variable
String photofilepath;
byte[] candidate_image = null ;
    /**
     * Creates new form DocumentsCandidate
     */
    public DocumentsCandidate() {
        initComponents();
        conn=promaconnect.ConnecrDb();
       CurrentDateTime();
    }

     public DocumentsCandidate(String User) {
    username = User;
       initComponents();
       conn=promaconnect.ConnecrDb();
       CurrentDateTime();
    }
     
      public void CurrentDateTime(){
        Calendar cal= new GregorianCalendar();
        //to display date and time 
        int month =cal.get(Calendar.MONTH);
        int year =cal.get(Calendar.YEAR);
        int day =cal.get(Calendar.DAY_OF_MONTH);
        date_txt1.setText(day+"."+(month+1)+"."+year); /* month +1 is used to start month from 1 not from 0 */
        
        int sec =cal.get(Calendar.SECOND);
        int hr =cal.get(Calendar.HOUR_OF_DAY);
        int min =cal.get(Calendar.MINUTE);
        time_txt1.setText(hr+":"+(min));
        
    }
    /**     * WARNING: Do NOT modify this code. The content of this method is always

     * This method is called from within the constructor to initialize the form.
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        date_txt1 = new javax.swing.JLabel();
        time_txt1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        photo_attach_cmd = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        cv_attach_cmd = new javax.swing.JButton();
        others_attach_cmd = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        resume_attach_cmd = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        path_photo_txt = new javax.swing.JTextField();
        path_coverLetter_txt = new javax.swing.JTextField();
        path_resume_txt = new javax.swing.JTextField();
        path_others_txt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        date_txt1.setBackground(new java.awt.Color(51, 51, 255));
        date_txt1.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        date_txt1.setText("Date");

        time_txt1.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        time_txt1.setText("Time ");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel1.setText("Upload your Documents");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel2.setText("Photo ");

        photo_attach_cmd.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        photo_attach_cmd.setText("Attach");
        photo_attach_cmd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                photo_attach_cmdActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel3.setText("Resume");

        cv_attach_cmd.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        cv_attach_cmd.setText("Attach");
        cv_attach_cmd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cv_attach_cmdActionPerformed(evt);
            }
        });

        others_attach_cmd.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        others_attach_cmd.setText("Attach");
        others_attach_cmd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                others_attach_cmdActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel4.setText("Others");

        resume_attach_cmd.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        resume_attach_cmd.setText("Attach");
        resume_attach_cmd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resume_attach_cmdActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel5.setText("Cover letter");

        path_photo_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                path_photo_txtActionPerformed(evt);
            }
        });

        path_coverLetter_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                path_coverLetter_txtActionPerformed(evt);
            }
        });

        path_resume_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                path_resume_txtActionPerformed(evt);
            }
        });

        path_others_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                path_others_txtActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Save-icon.png"))); // NOI18N
        jButton1.setText("Save ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cv_attach_cmd)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(photo_attach_cmd))))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(others_attach_cmd)
                                .addComponent(resume_attach_cmd)))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(path_photo_txt)
                    .addComponent(path_coverLetter_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
                    .addComponent(path_resume_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
                    .addComponent(path_others_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(11, 11, 11)
                            .addComponent(time_txt1))
                        .addComponent(date_txt1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(257, 257, 257))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(photo_attach_cmd)
                    .addComponent(path_photo_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cv_attach_cmd)
                    .addComponent(jLabel5)
                    .addComponent(path_coverLetter_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(resume_attach_cmd)
                        .addComponent(path_resume_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(others_attach_cmd)
                    .addComponent(jLabel4)
                    .addComponent(path_others_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(time_txt1)
                .addGap(6, 6, 6)
                .addComponent(date_txt1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-619)/2, (screenSize.height-398)/2, 619, 398);
    }// </editor-fold>//GEN-END:initComponents

    private void photo_attach_cmdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_photo_attach_cmdActionPerformed
        // To attach Photo to the Data base
        JFileChooser photo= new JFileChooser();
        photo.showOpenDialog(null);
        File photoName = photo.getSelectedFile();
               photofilepath= photoName.getAbsolutePath();
                path_photo_txt.setText(photofilepath);
               // This try catch block is used to covert the image into BLOB (Binary Large Object)
               
                try{
                    
                File image = new File(photofilepath); 
                FileInputStream filIpStr = new FileInputStream(image);
                ByteArrayOutputStream byArrOpStr= new ByteArrayOutputStream();
                byte[] temp= new byte[1024]; // setting the size of the memory 1MB 
                for(int readArray ; (readArray = filIpStr.read(temp))!=-1;){    // readArray is to copy the Photo data which is in 
                                                                               // byte form in 
                   byArrOpStr.write(temp,0, readArray); 
                               
                }
                candidate_image =byArrOpStr.toByteArray();
                        }catch(Exception e ){
                    JOptionPane.showMessageDialog(null,e);
                
                
                }
        
    }//GEN-LAST:event_photo_attach_cmdActionPerformed

    private void path_photo_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_path_photo_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_path_photo_txtActionPerformed

    private void cv_attach_cmdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cv_attach_cmdActionPerformed
        // To attach Coverletter to the Data base
        JFileChooser cv= new JFileChooser();
        cv.showOpenDialog(null);
        File coverLetter = cv.getSelectedFile();
                String coverLetterfilepath= coverLetter.getAbsolutePath();
                path_coverLetter_txt.setText(coverLetterfilepath);
    }//GEN-LAST:event_cv_attach_cmdActionPerformed

    private void path_coverLetter_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_path_coverLetter_txtActionPerformed
        
    }//GEN-LAST:event_path_coverLetter_txtActionPerformed

    private void path_resume_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_path_resume_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_path_resume_txtActionPerformed

    private void path_others_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_path_others_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_path_others_txtActionPerformed

    private void resume_attach_cmdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resume_attach_cmdActionPerformed
        // To attach resume to the Data base
        JFileChooser res= new JFileChooser();
        res.showOpenDialog(null);
        File resume = res.getSelectedFile();
                String resumefilepath= resume.getAbsolutePath();
                path_resume_txt.setText(resumefilepath);  // to show the path of the file in the text field in gui
              
    }//GEN-LAST:event_resume_attach_cmdActionPerformed

    private void others_attach_cmdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_others_attach_cmdActionPerformed
     // To attach others to the Data base
        JFileChooser other= new JFileChooser();
        other.showOpenDialog(null);
        File others = other.getSelectedFile();
                String othersfilepath= others.getAbsolutePath();
                path_others_txt.setText(othersfilepath);
    }//GEN-LAST:event_others_attach_cmdActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        try{
    
          String Sql = "update CandidateProfile set Image= ? where UserName ='"+username+"'" ;
            pst = conn.prepareStatement(Sql);
            pst.setBytes(1, candidate_image); // to update the field of image with BLOB data 
            pst.execute();
            JOptionPane.showMessageDialog(null,"Documents uploaded sucessfully");
        
        }catch (Exception e){
                 JOptionPane.showMessageDialog(null,e);
                } 
    }//GEN-LAST:event_jButton1ActionPerformed
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
           /*  for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }*/UIManager.setLookAndFeel("com.jtattoo.plaf.mcwin.McWinLookAndFeel");
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DocumentsCandidate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DocumentsCandidate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DocumentsCandidate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DocumentsCandidate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DocumentsCandidate().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cv_attach_cmd;
    private javax.swing.JLabel date_txt1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton others_attach_cmd;
    private javax.swing.JTextField path_coverLetter_txt;
    private javax.swing.JTextField path_others_txt;
    private javax.swing.JTextField path_photo_txt;
    private javax.swing.JTextField path_resume_txt;
    private javax.swing.JButton photo_attach_cmd;
    private javax.swing.JButton resume_attach_cmd;
    private javax.swing.JLabel time_txt1;
    // End of variables declaration//GEN-END:variables
}
